# Generated by Django 5.1.3 on 2025-03-07 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreasTecnologicas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area_tecnologica', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('dt_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Financiador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('financiador', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('projeto', models.CharField(max_length=100)),
                ('coordenador', models.TextField(max_length=100)),
                ('ativo', models.BooleanField()),
                ('inicio_vigencia', models.DateField()),
                ('fim_vigencia', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11)),
                ('area_tecnologica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.areastecnologicas')),
                ('equipe', models.ManyToManyField(to='projects.colaborador')),
                ('financiador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.financiador')),
            ],
        ),
    ]
