# Generated by Django 5.1.3 on 2025-03-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AreasTecnologicas',
            new_name='AreaTecnologica',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='nome',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
